<a href="https://colab.research.google.com/github/vyron-arvanitis/pytorch_tutorials/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Tue Jan 20 21:24:52 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


In [ ]:
# scalar
scalar = torch.tensor(7)
print(scalar.ndim, scalar.shape, scalar.item())

0 torch.Size([]) 7


In [ ]:
# vector
vector = torch.tensor([1,2])
print(vector.ndim, vector.shape, vector)

1 torch.Size([2]) tensor([1, 2])


In [ ]:
# MATRIX

MATRIX = torch.tensor([[1,2],[3,4]])
print(MATRIX.ndim, MATRIX.shape, MATRIX)

2 torch.Size([2, 2]) tensor([[1, 2],
        [3, 4]])


In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])
print(TENSOR[0][0])
print(TENSOR[0][0][0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [ ]:
# RANDOM TENSOR
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)
print(torch.rand(1,1,1))

tensor([[0.1427, 0.8291, 0.1522, 0.3539],
        [0.7750, 0.4470, 0.0042, 0.7621],
        [0.5169, 0.6899, 0.9839, 0.6440]])
2
torch.Size([3, 4])
tensor([[[0.3773]]])


In [ ]:
# create random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # H, W, C (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [ ]:
# Tenosr only 0s
zeros = torch.zeros(size=(3,4))
print(zeros*random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# Tensor of only 1s
ones = torch.ones(size=(3,4), dtype=int)
ones


tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
ones.dtype

torch.int64

### Range of tensors

In [ ]:
# torch.arange
one_to_tem = torch.arange(start=1, end=11, step=1)
one_to_tem, one_to_tem.ndim, one_to_tem.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 1, torch.Size([10]))

In [ ]:
# Tensor like
ten_zeros = torch.zeros_like(input=one_to_tem)
ten_ones = torch.ones_like(input=one_to_tem)
ten_ones, ten_zeros

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

### Tensor datatypes

In [ ]:
# FLoat 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0 , 9.0],
                               dtype=torch.float32,
                               device=None,
                               requires_grad=False # track gradients with this tensors operations
                               )
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
print(float_32_tensor, float_32_tensor.dtype)
print(float_16_tensor, float_16_tensor.dtype)

tensor([3., 6., 9.]) torch.float32
tensor([3., 6., 9.], dtype=torch.float16) torch.float16


In [ ]:
new_float_16_tensor = float_32_tensor.type(torch.float16)
new_float_16_tensor.dtype

torch.float16

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting info from Tensors Attribtues

1.   Tensor not right datatype - use `tensor.dtype`
1.   Tensor not right shape - use `tensor.shape`
2.   Tensor not right device - use `tensor.device`



In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0363, 0.7827, 0.9876, 0.6581],
        [0.9710, 0.4435, 0.8758, 0.7879],
        [0.0806, 0.2421, 0.4872, 0.7504]])

In [ ]:
some_tensor.size() == some_tensor.shape

True

In [ ]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of some tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0363, 0.7827, 0.9876, 0.6581],
        [0.9710, 0.4435, 0.8758, 0.7879],
        [0.0806, 0.2421, 0.4872, 0.7504]])
Datatype of some tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

* Addition
* Subtraction
* Multiplicaiton (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Matrix Multiplication
print(torch.matmul(tensor, tensor) )
print(tensor @ tensor)
print(torch.matmul(tensor, tensor) == tensor @ tensor)

tensor(14)
tensor(14)
tensor(True)


In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.01 ms, sys: 0 ns, total: 1.01 ms
Wall time: 992 µs


In [ ]:
%%time
for i in range(10000):
  tensor @ tensor

CPU times: user 26.1 ms, sys: 973 µs, total: 27.1 ms
Wall time: 28.1 ms


In [ ]:
%%time
for i in range(10000):
  torch.matmul(tensor, tensor)

CPU times: user 28.4 ms, sys: 0 ns, total: 28.4 ms
Wall time: 28.5 ms


In [ ]:
tensor_A = torch.rand(size=(3,2))
tensor_A.shape

torch.Size([3, 2])

In [ ]:
tensor_B = torch.rand(size=(3,2))
tensor_B.shape

torch.Size([3, 2])

In [ ]:
try:
    tensor_A @ tensor_B
except RuntimeError as e:
    print(f"Caught expected RuntimeError: {e}")
    print("Matrix multiplication failed due to incompatible shapes.")
else:
    print("Matrix multiplication succeeded unexpectedly.")

Caught expected RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
Matrix multiplication failed due to incompatible shapes.


In [ ]:
tensor_A @ tensor_B.T

tensor([[0.6217, 0.5398, 0.5670],
        [0.2825, 0.3190, 0.1584],
        [0.2701, 0.1764, 0.3247]])

## Finding min, max, mean, sum etc....

In [ ]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
torch.mean(x, dtype=torch.float32), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
%%time
torch.sum(x)

CPU times: user 195 µs, sys: 27 µs, total: 222 µs
Wall time: 197 µs


tensor(450)

In [ ]:
# Find the sum
%%time
x.sum()

CPU times: user 326 µs, sys: 0 ns, total: 326 µs
Wall time: 267 µs


tensor(450)

## Find the positional min and max (argmin or argmax)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> index position of target tensor wher eminimum value occurs
x.argmin() ,x[0]

(tensor(0), tensor(0))

In [ ]:
# Find the position in tensor taht ahs the max value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Returna view of an input tensor of certain sahpe but keep the **same memory** as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack or h stack)
* Squeeze - removes all `1` deminsions from a tensor
* Unsqueeze - add a `1` dimension to a target tensors
* Permute - Returna view of the input witih  dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changin z changes x (becuase the view of hte tensor shares the same memor yas the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stack = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stack

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]))

In [ ]:
# torch.squeeze()
print(f" Previous tensor: {x_reshaped}")
print(f" Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\n New tensor: {x_squeezed}")
print(f" New shape: {x_squeezed.shape}")

 Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
 Previous shape: torch.Size([1, 9])

 New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
 New shape: torch.Size([9])


In [ ]:
# torch.squeeze()
print(f" Previous tensor: {x_squeezed}")
print(f" Previous shape: {x_squeezed.shape}")

x_unsqueeze = x_squeezed.unsqueeze(dim=1)
# Add an extra dimension
print(f"\n New tensor: {x_unsqueeze}")
print(f" New shape: {x_unsqueeze.shape}")

 Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
 Previous shape: torch.Size([9])

 New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
 New shape: torch.Size([9, 1])


In [ ]:
# torch.permute - rearrange the dimension of tensor i na specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to bring colors in front
x_permuted = x_original.permute(2, 0, 1) # shifts
print(f" The original shape is {x_original.shape}")
print(f" The permuted shape is {x_permuted.shape}")

 The original shape is torch.Size([224, 224, 3])
 The permuted shape is torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0,] = 1234
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(1234.), tensor(1234.))

## Indexing

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# index on dim=0
x[0], x[0].shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
# index on dim=1
x[0, 0] , x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# index on dim=2
x[0,0,0,], x[0][0][0], x[0, 2, 2]

(tensor(1), tensor(1), tensor(9))

In [ ]:
# Use ":" to select "all" of a target deimensions

x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of the 0 and 1st dim but only index 1 of 2nd dim
x[:, : , 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of 0 dim but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimensio nadn al lvalues of the 2nd dimension
x[0, 0, : ]

tensor([1, 2, 3])

In [ ]:
# index x to return 9 and index to get 3,6,9
x[0][2][2], x[0, :, 2], x[:, :, 2]

(tensor(9), tensor([3, 6, 9]), tensor([[3, 6, 9]]))

## PyTorch tensors and NumPy

* Data in NumPy,-> PyTorch -> `torch.from_numpy(ndarray)
* PyTorch -> NymPy-> `torch.Tensor.numpy()

In [ ]:
# NumPy array to tensor
import numpy as np
import torch

array = np.arange(1.0, 8.0) # defualt numpy dtype is float64
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
 # change the value of the array, what happens? to the `tensor`
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor what happens to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [ ]:
import torch

# create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B =torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.3250, 0.9079, 0.1572, 0.7870],
        [0.9734, 0.2682, 0.5583, 0.1234],
        [0.1029, 0.2587, 0.6165, 0.7133]])
tensor([[0.7048, 0.9786, 0.2401, 0.9826],
        [0.4813, 0.0485, 0.1791, 0.2536],
        [0.2763, 0.9456, 0.6008, 0.8075]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# make them reproducible
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Runing tensors and PyTorch objects on the GPUs



In [ ]:
!nvidia-smi

Tue Jan 20 21:25:21 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for gpu access with pytorch

In [ ]:
import torch
torch.cuda.is_available()

True

# Setup a device agnostic code

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of GPUs
torch.cuda.device_count()

1

## putting tensors and models on the GPU

We want them on teh GPU for faster computation

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to the GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Move tensors back to the cpu

In [ ]:
# If tensor on GPU, cannot transform it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# TO fix the above error use `Tensor.cpu()`
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

tensor([1, 2, 3])